-- Per-user Google OAuth tokens for Calendar API access.
--
-- Each authenticated user can connect their Google Calendar via the
-- /auth/google/start → consent → /auth/google/callback flow. The flow
-- requests offline access (refresh_token) with calendar.readonly scope;
-- we persist the refresh_token here and exchange it for short-lived
-- access tokens at request time inside calendar_fetch.py.
--
-- Replaces the global pickled token previously generated by setup_gcal.py
-- (one shared developer calendar shown to every user). The pickle is now
-- only used as a last-resort fallback for unauthenticated /context cron
-- runs; user-facing /calendar reads exclusively from this table.
--
-- Encryption-at-rest is provided by Supabase Postgres. Refresh tokens are
-- still sensitive: RLS lets only the owning user read their row, and the
-- backend reaches the table through the service_role key (bypasses RLS,
-- but the connection is server-side and never reaches the browser).
-- Application-layer encryption is a deliberate "later" — file an issue
-- before storing tokens for any non-readonly scope.

CREATE TABLE IF NOT EXISTS google_tokens (
    user_id        UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    refresh_token  TEXT NOT NULL,
    access_token   TEXT,
    expires_at     TIMESTAMPTZ,
    scope          TEXT,
    google_email   TEXT,
    connected_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE google_tokens ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users read their own google_tokens"
    ON google_tokens FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "users delete their own google_tokens"
    ON google_tokens FOR DELETE
    USING (auth.uid() = user_id);

-- Backend writes/upserts go through the service_role key from
-- /auth/google/callback. No INSERT/UPDATE policy for the anon role —
-- the OAuth callback is the only legitimate writer.

COMMENT ON TABLE google_tokens IS
    'Per-user Google OAuth refresh tokens for Calendar API. One row per connected user.';
